CREATE DATABASE IF NOT EXISTS frota_ferroviaria CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE frota_ferroviaria;

CREATE TABLE IF NOT EXISTS usuario (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    login VARCHAR(80) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    papel VARCHAR(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
